### ISSUE TITLE
Loading font crash

### ISSUE THREAD

**Issue by BookerSoft** [texus/TGUI.Net#7]
Why is it trying the wrong call when i use the one with string file name.
 
Dotnet 9
Tgui.net 1.7.0 beta
Vscodium
Win 11 
Mesa3d
QXL or Vvirtio do adapter in uefi vm

**Comment by texus** [comment]
Are you certain the font file exists in the right place?
I only managed to reproduce a crash when using a wrong filename. If I use an absolute filename or place the font next to the csproj then I don't get a crash and the font is correctly loaded.

I'll update the code to throw a C# exception instead of crashing, as even with a wrong filename a crash is undesired.

**Comment by BookerSoft** [comment]
Yes was loading from windows fonts and the app folder, will try adding to project and see if that fixes it.

Do I need any other DLLs in the build folder?

**Comment by texus** [comment]
I've published version `1.8.0-rc` which at least throws an exception when loading fails.
I'll keep this issue open until you confirmed that loading a font works when added to your project.

> was loading from windows fonts

Neither SFML nor TGUI supports that, so that currently wouldn't work.

> Do I need any other DLLs in the build folder?

No. Having a `PackageReference` in your project for `TGUI.Net` will place the tgui.net.dll and the SFML.Net dll files next to your exe, as well as adding the CSFML and CTGUI native dll files in the runtimes folder. So you wouldn't need to copy any dll yourself.

**Comment by BookerSoft** [comment]
Still have an issue with loading font through TGUI.Net maybe add a variable in the TGUI.Font that has type SFML.Graphics.Font so that GUI font can point to that. As sfml does not cause unhandled exception when loading the font.

**Comment by texus** [comment]
Can you try with TGUI.Net 1.8.0-rc and see what the error message is now?
The only reason why it should throw an exception is if the file can't be found.

**Comment by BookerSoft** [comment]
It is executionengineexception when loading using TGUI.Font it seems that it still errors at tguifont.createfromfile. How do I use sfml.graphics.font on gui?
Is there a way to cast to TGUI.Font?

![image](https://github.com/user-attachments/assets/72403e1e-5e44-4221-9e5a-5125978dd027)

**Comment by texus** [comment]
> it still errors at tguifont.createfromfile

Does Vscodium show where the code crashes? Is the `tguiFont_createFromFile` line where it crashes inside the `CreateFontFromFileImpl` function?

Does the font name contain any special characters?

Does it also crash when you use an absolute path for the font?

> QXL or Vvirtio do adapter in uefi vm

I'm not certain what you mean with this. Are you running the code in a VM? If so, does the crash only occur in that case or also when running the program natively on your pc?

> How do I use sfml.graphics.font on gui? Is there a way to cast to TGUI.Font?

You can't. `TGUI.Font` and `SFML.Graphics.Font` are two completely separate things.

**Comment by BookerSoft** [comment]
Terminal output 
![image](https://github.com/user-attachments/assets/b0a270c3-9188-4a65-aa94-1967d2ac8bba)

**Comment by texus** [comment]
The problem here is likely caused because you are creating the font before creating the Gui object.

The `TGUI.Gui` object must be constructed before creating other TGUI objects.

**Comment by BookerSoft** [comment]
Now I don't get exceptions but gui not showing any text.
What should I do?

**Comment by texus** [comment]
Can you show your code?

**Comment by BookerSoft** [comment]
Here are photos of code![image](https://github.com/user-attachments/assets/3346f0a2-8227-4c23-8b5a-c5f59b121faf)

![image](https://github.com/user-attachments/assets/86ae7d95-7e56-45cf-a014-fd46620a2ade)
![image](https://github.com/user-attachments/assets/e49ea654-ecf0-43a6-8a9f-ae03d6f64a45)

**Comment by texus** [comment]
Are the backgrounds of the buttons being rendered with only the text missing? Or is nothing rendered at all?

Could you share your full code somewhere, or create a new small program that has the same issue? Then I could copy the code here and see what is happening exactly.

**Comment by BookerSoft** [comment]
- - Here is code for main menu

https://drive.google.com/file/d/1_NGrIIEeKd70jmDfdupiHDBUD9zOZO_y/view?usp=sharing

**Comment by texus** [comment]
I'm unable to reproduce the issue with that code.

I added it to a project with minor tweaks (because I e.g. don't have the Support class) and it displays text just fine. The button text is unreadable because it's a white text on a white background, but it becomes black on hover and I can see the "City Tycoon" label above the button.
I had to call PrepareMenu twice in my code, once without a font and once with a font. Otherwise it would crash because `buttons[0].Renderer.Font` would be assigned before `buttons[0] = new TGUI.Button();` was executed.

If you can't find the issue then please minimize the code to a simple program consisting of only a single source file. Then I can copy and run the identical code here without having to make modifications that might change what the code does.

**Comment by BookerSoft** [comment]
Now that is fixed but it seems keyboard key events are not being handled when a gui is drawn. Is there a way to tell the gui what to do if a key is pressed?

This is for key binding.

**Comment by texus** [comment]
Can you explain the issue with some more details?
Which keys aren't being handled? Do you mean the gui should handle them but doesn't, or do you mean your code doesn't receive an event about the key presses?

Both typing text in an edit box and receiving key events from the window with the code below work fine for me.
```C#
window.KeyPressed += (s, args) => Console.WriteLine("Key pressed");
```

**Comment by BookerSoft** [comment]
My issue is that keypresses to control the game and gui are ignored once gui is drawn.
Where does s come from in the line of code.

**Comment by texus** [comment]
Key bindings and key presses to control the game all sound like part of your own code. I can't help you if you don't provide enough information.

Please provide code of a small sample program that shows what you are doing.
How are you handling key events?
What does the code do when the gui isn't drawn?

>  Where does s come from in the line of code.

Event handlers typically have 2 parameters, a sender and event arguments. That line contains a lambda expressions, so it is creating an anonymous functions that has those 2 parameters. The `s` is the parameter name that will contain the sender, which I assume will be the window in this case.

**Comment by BookerSoft** [comment]
I call the guis main loop function before opening my window and keyboard events don't work should I just draw it in my main loop?
Key events work when not calling mainloop function and not drawing gui.

**Comment by texus** [comment]
You don't need the `MainLoop` functio, it exists for cases where you wouldn't have your own main loop. The `window.DispatchEvents()` wouldn't be called in that case, which would explain why you don't receive events (not just key events).

You only need `gui.Draw();` inside your `window.IsOpen` loop.

**Comment by BookerSoft** [comment]
Now I get DLL loading exception when running on windows, package seems to be missing sfml, csfml and TGUI DLLs in runtime folders for windows-x86 and x64 with 1.8.0-rc

**Comment by texus** [comment]
The package never contained these dlls. It only contains CTGUI, which links statically to TGUI. The CSFML and SFML dlls come with the SFML.Net dependency.

I did notice that I created a `1.8.0.1-rc` version two weeks ago to change the dependency from SFML.Net 2.6.0 to 2.6.1 but didn't upload it. I'm uploading the package right now, maybe that already helps.

Edit: I can run a sample program here with either 1.8.0-rc or 1.8.0.1-rc without errors.

**Comment by BookerSoft** [comment]
Do I need vcruntime or not?

**Comment by texus** [comment]
You probably do need the Microsoft Visual C++ Runtime Redistributable installed. It's already required by CSFML though.
